local path = ...
require (path .. ".api")
require (path .. ".constants")
require (path .. ".bit_ex")
require (path .. ".table_ex")
require (path .. ".string_ex")
require (path .. ".math_ex")
utf8 = require("utf8")
require (path .. ".object")
Timer = require (path .. ".timer")
require (path .. ".vector")
require (path .. ".json")
require (path .. ".utilities")
require (path .. ".input")
require (path .. ".events")
require (path .. ".ui")
require (path .. ".texture")
require (path .. ".imgui")

-- Testing
require (path .. ".testing")
require (path .. ".tests")